version: '3'

services:
  proxy:
    image: nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=node_be
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ex28
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    image: ex2.8-be
    build: ./be
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=node_be
      - DB_PASSWORD=secret
      - DB_NAME=ex28
      - DB_HOST=postgres

  frontend:
    image: ex2.8-fe
    build: ./fe

volumes:
  redis_data:
  database: