version: '3'

services:
  proxy:
    image: nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  redis:
    image: redis:latest
    volumes:
      - ./redis:/data

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=node_be
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ex210
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    image: ex2.10-be
    build: ./be
    restart: on-failure
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=node_be
      - DB_PASSWORD=secret
      - DB_NAME=ex210
      - DB_HOST=postgres

  frontend:
    image: ex2.10-fe
    build: ./fe
    environment:
      - API_URL=/api